// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdWLwfQVnB824ahda511Jap5o3Uu24kE',
    appId: '1:882191572726:web:e0fb12917be00e1d0e16d7',
    messagingSenderId: '882191572726',
    projectId: 'ujikom-e3a9c',
    authDomain: 'ujikom-e3a9c.firebaseapp.com',
    databaseURL: 'https://ujikom-e3a9c-default-rtdb.firebaseio.com',
    storageBucket: 'ujikom-e3a9c.appspot.com',
    measurementId: 'G-94EMXMHFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaVhZZ9MdnIulez7gZKt3MpHU5yOlsBEg',
    appId: '1:882191572726:android:41d04086817c50560e16d7',
    messagingSenderId: '882191572726',
    projectId: 'ujikom-e3a9c',
    databaseURL: 'https://ujikom-e3a9c-default-rtdb.firebaseio.com',
    storageBucket: 'ujikom-e3a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjn-SpABLt6n5RJSGvjRyCaBv9o9pdQc',
    appId: '1:882191572726:ios:eb355a887bb5839b0e16d7',
    messagingSenderId: '882191572726',
    projectId: 'ujikom-e3a9c',
    databaseURL: 'https://ujikom-e3a9c-default-rtdb.firebaseio.com',
    storageBucket: 'ujikom-e3a9c.appspot.com',
    iosBundleId: 'com.example.ujikom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpjn-SpABLt6n5RJSGvjRyCaBv9o9pdQc',
    appId: '1:882191572726:ios:0cd7752bb18a9dd40e16d7',
    messagingSenderId: '882191572726',
    projectId: 'ujikom-e3a9c',
    databaseURL: 'https://ujikom-e3a9c-default-rtdb.firebaseio.com',
    storageBucket: 'ujikom-e3a9c.appspot.com',
    iosBundleId: 'com.example.ujikom.RunnerTests',
  );
}
